travis:
  secure:
    BINSTAR_TOKEN: UadJI9wKn5EBN2t9IosoLsWYMWZgZHY094GoZgnBbx9BzNVxca9uTSHR/M2WusKZ3b5I9PSdhPYrw/NxbBWFD/CjCH0eTgAhWAm8krjKyiF0LVFdrKiHmDwAik+f7pnFoSkBohmv6sGdzsiu3P4mHnxsncv0jgTt/MsyPiYAzliP6X+vwWgLmoVvHLOdE8DgyKwkycirnLq2A8c8rCu9gcZPcYlXMwPSbHPXHJORUK3YagDoWXFt5E2attfuMk9KxXTiMhYnTxXB4KsyizloFAmB0R9cfocTwgy1hRYl18cGhoY8hF5StVYizhWNV0LxCJLGF4JMHXX6dVByEAefBCNm0hlN07A05/KioqZBZ207f4ANJtAGZiAB/7elCSGVIB/F9f+Tiry75oKTTx+4mm0d2xDSeZMIkCQBg3ePC6akyaqgDn/OKvNMNJ1ynZJE0hcu8VvBRUXQtfKJOa3KDdnpWx3n/6kxKjuVZfAXdgcDoSPxTCGoux7pf8vY+XxKzkOTZGKbVRpvpEuz5CBrZvXTiNCVK7XlPWogZIRx7VtbQIfKNJf4qxkyeqbd9bo2J7SoG+f329i43D0zat6mo08Xd4bz44NqjLD3Dq94WURHD6KSa5LyUaOOhzgsAzhh3Z/XmJmyDSuHnNooILTav/ima8cmn+ceMG8WJZ5503U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
